apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    io.kompose.service: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  # The port the mysqldb pod is listening on