apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: q2a-web
  name: q2a-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: q2a-web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/q2a-q2a-net: "true"
        io.kompose.service: q2a-web
    spec:
      containers:
        - env:
            - name: QA_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysqldb-config
                  key: MYSQL_DATABASE
            - name: QA_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: MYSQL_PASSWORD
            - name: QA_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysqldb-config
                  key: MYSQL_USER
          image: mara14/q2a-web:latest
          name: q2a-web
          ports:
            - containerPort: 80
              hostPort: 9891
              protocol: TCP
      restartPolicy: Always
